- name: Restart iscsid.
  ansible.builtin.systemd:
    name: "{{ service }}"
    state: restarted
  loop:
    - iscsid.service
    - iscsi.service
  loop_control:
    loop_var: service

- name: Remount filesystems.
  ansible.builtin.systemd:
    name: "{{ mount }}.mount"
    state: restarted
    daemon_reload: true
  loop:
    - volumes
    - backup
    - var-lib-docker
  loop_control:
    loop_var: mount

- name: Restart monitoring.
  community.docker.docker_compose:
    project_src: "~/docker-compose/monitoring"
    restarted: true
