- hosts: servicepi
  become: true
  vars_files:
    - config.yml
    - secrets.yml
  pre_tasks:
    - name: Update pacman cache.
      community.general.pacman:
        update_cache: true
  handlers:
    - name: Include handlers.
      ansible.builtin.import_tasks: handlers.yml
  tasks:
    - name: Set up docker.
      ansible.builtin.import_tasks: tasks/docker.yml
    - name: Set up iscsi.
      ansible.builtin.import_tasks: tasks/iscsi.yml
    - name: Mount additional filesystems.
      ansible.builtin.import_tasks: tasks/mount.yml
    - name: Start containers.
      ansible.builtin.import_tasks: tasks/containers.yml
