- name: Install btrbk.
  kewlfft.aur.aur:
    name:
      - btrbk
      - mbuffer
    state: present
  become: true
  become_user: aur_builder

- name: Create btrbk config dir.
  ansible.builtin.file:
    path: /etc/btrbkt
    state: directory
    mode: "0700"

- name: Copy btrbk config files.
  ansible.builtin.copy:
    src: files/btrbk-volumes.conf
    dest: /etc/btrbk/volumes.conf
    mode: "0700"
