- name: Create folder for docker-compose file.
  ansible.builtin.file:
    path: "~/docker-compose/{{ stack }}"
    state: directory
    recurse: true
    mode: "0700"
  loop:
    - nextcloud
  loop_control:
    loop_var: stack

- name: Generate docker-compose files.
  ansible.builtin.template:
    src: templates/{{ stack }}-docker-compose.yml.j2
    dest: ~/docker-compose/{{ stack }}/docker-compose.yml
    mode: "0600"
  loop:
    - nextcloud
  loop_control:
    loop_var: stack

- name: Start containers.
  community.docker.docker_compose:
    project_src: "~/docker-compose/{{ stack }}"
    pull: true
  loop:
    - nextcloud
  loop_control:
    loop_var: stack